version: '3'

services:
  app:
    container_name: 'monitoring-voucher-app'
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/app
    #   - node_modules:/app/node_modules
    environment:
      - PORT=5002
    ports:
      # #prod
      # - "8096:4002"
      # dev
      - "9106:5002"
    
    networks:
      - monitoring
    command: ["serve", '-s', "build"]

networks:
  monitoring:
    driver: bridge

