name: Deploy to Development

on:
  push:
    branches:
      - production # Triggers on pushes to the development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for deployment
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}

      # Step 3: Deploy Docker Compose app
      - name: Deploy Docker Compose app
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD_DEV }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_USER_DEV }}@${{ secrets.SERVER_HOST_DEV}}" << 'EOF'
          echo "Connected to the server"
          # Step 3.1: Navigate to the project directory
          cd /var/www/backend-voucher/backend-cms-voucher  # Replace with the path to your project

          # Step 3.3: Pull the latest changes from GitHub (development branch)
          git pull origin development

          # Step 3.4: Rebuild and restart the Docker container
          docker-compose down -v
          docker-compose up --build -d
          EOF
